### PR TITLE
feat: support yarn

### PR DESCRIPTION
**Pull request by PuneetGopinath**

### CODE REVIEW

**Review by abhijoshi2k — COMMENTED** [review]
You should not have lock file of yarn and npm both. Keep any one.

**Comment by PuneetGopinath** [comment]
> You should not have lock file of yarn and npm both. Keep any one.

Okay

**Comment by PuneetGopinath** [comment]
@abhijoshi2k If I now delete the package-lock.json then I need to update in workflows also know?

**Comment by abhijoshi2k** [comment]
> @abhijoshi2k If I now delete the package-lock.json then I need to update in workflows also know?

Yes. But i don't know if workflows support yarn

**Comment by PuneetGopinath** [comment]
I will do this slowly, check the other pr

**Review by abhijoshi2k — APPROVED** [review]

**Pull request merged**
